export const smartGasPage = {
  badge: "GAS METERS",
  title: "PRODUCT OVERVIEW",
  paragraphs: [
    "The SAAIR Smart LoRa RF Prepaid Split Keypad Gas Meter is an intelligent diaphragm gas metering solution designed for prepaid and postpaid residential and light commercial gas distribution networks. It combines accurate gas measurement with Secure Token (STS) prepaid technology, wireless LoRa RF communication, remote monitoring, and automatic shut-off capabilities to support modern utility management.",
    "The meter is intended for low-pressure gas distribution systems and provides reliable measurement, tamper detection, and remote management through an Advanced Metering Infrastructure (AMI) platform.",
  ],
  descriptionTitle: "Product Description",
  componentsLead: "The meter consists of two primary components:",
  primaryComponents: ["Smart Gas Meter", "Customer Interface Unit (CIU)"],
  meterBody:
    "The gas meter measures gas consumption and controls gas delivery through an integrated motorized shut-off valve.",
  ciuLead:
    "The CIU is installed inside the customer’s premises, allowing users to:",
  ciuPoints: [
    "Enter recharge tokens",
    "View remaining gas credit",
    "Monitor consumption",
    "Access meter information",
    "Receive alarms and notifications",
  ],
  communication:
    "Communication between the meter and CIU is achieved through 433 MHz LoRa RF wireless communication.",
  specifications: [
    {
      title: "Mechanical Specifications",
      headers: ["Parameter", "Specification"],
      rows: [
        ["Installation", "Vertical"],
        ["Gas Flow Direction", "Left to Right"],
        ["Total Length", "277 ±0.5 mm"],
        ["Meter Length", "235 ±0.5 mm"],
        ["Dimensions", "230.5 × 173 × 134.6 mm"],
        ["Shell Size", "192 × 133 × 43.5 mm"],
        ["Pipe Diameter", "21.4 ±0.2 mm"],
        ["Protection Rating", "IP67"],
      ],
    },
    {
      title: "Metering Specifications",
      headers: ["Parameter", "G1.6", "G2.5"],
      rows: [
        ["Nominal Flow", "1.6 m³/h", "2.5 m³/h"],
        ["Maximum Flow", "2.5 m³/h", "4.0 m³/h"],
        ["Minimum Flow", "0.016 m³/h", "0.025 m³/h"],
        ["Accuracy Class", "Class 1.5", "Class 1.5"],
        ["Resolution", "0.01 m³", "0.01 m³"],
        ["Maximum Reading", "9,999.999 m³", "9,999.999 m³"],
      ],
    },
    {
      title: "Communication Specifications",
      headers: ["Parameter", "Specification"],
      rows: [
        ["Technology", "LoRa RF"],
        ["Frequency", "433 MHz"],
        ["CIU Range", "Up to 350 m"],
        ["DCU Range", "Up to 1,000 m"],
        ["Communication Type", "Wireless"],
        ["Network Support", "AMI"],
        ["API Support", "Yes"],
      ],
    },
    {
      title: "Electrical Specifications",
      headers: ["Parameter", "G1.6"],
      rows: [
        ["Battery Type", "ER18505 Lithium"],
        ["Voltage", "3.6 V"],
        ["Battery Replaceable", "Yes"],
        ["Expected Battery Life", "6–8 Years"],
        ["Working Current", "≤1.1 mA"],
        ["Sleep Current", "≤12 µA"],
      ],
    },
    {
      title: "Environmental Specifications",
      headers: ["Parameter", "Specification"],
      rows: [
        ["Operating Temperature", "−10°C to +40°C"],
        ["Maximum Working Pressure", "50 kPa"],
        ["Installation Position", "Vertical"],
        ["Protection Rating", "IP67"],
      ],
    },
  ],
  componentsTitle: "PRODUCT COMPONENTS",
  externalTitle: "External Components:",
  externalComponents: [
    "High-strength polymer enclosure",
    "Corrosion-resistant aluminum metering chamber",
    "LCD display",
    "Directional flow indicator",
    "Mounting points",
    "Battery compartment",
    "Inlet connection",
    "Outlet connection",
  ],
  internalTitle: "Internal Components:",
  internalComponents: [
    "Mechanical gas measurement module",
    "Metering chamber",
    "Rubber piston shut-off valve",
    "Lithium battery",
    "LoRa RF communication module",
    "STS controller",
    "Tamper detection circuitry",
    "LCD driver",
    "Main PCB",
  ],
} as const;
